---
title: "Examine Life Expectancy"
author: "Chang Liu"
date: "9/6/2021"
output: html_document
html_document :
df_print: paged
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Load tidyverse and gapminder packages
library(tidyverse)
library(gapminder)

# Load gapminder_unfiltered
data("gapminder_unfiltered")
```


# Abstract

Here, I re-examined the analysis of Oeppen and Vaupel (2002).

# Life Expectancy Analysis

This was on the branch of testname
I have even updated it more
and even more so
deleted conflict headers

```{r}

# Maximum Life Expectancy for each year and country which had the maximum life expectancy
# Save result to sumdat

gapminder_unfiltered %>% 
  group_by(year) %>% 
  filter(lifeExp == max(lifeExp)) %>%
  ungroup() %>% 
  select(year, country, lifeExp) %>% 
  arrange(year) ->
  sumdat

```

new plot
```{r}

sumdat %>%
  ggplot(aes(x = year, y = lifeExp)) +
  geom_point(aes(color = country)) +
  geom_point(pch = 1) +
  theme_bw() +
  geom_smooth(method = "lm", se = FALSE) +
  xlab("Year") +
  ylab("Maximum Life Expectancy") +
  scale_color_discrete(name = "Country")

```

